name = "PolySet"
uuid = "ebb14b32-f2e0-4d83-93bc-77fe330ff378"
authors = ["Théo Duez", "CNRS"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
